project:
  type: book

book:
  #title: "Apuntes guía Expresión Gráfica <br>  Grupo investigación <a href='https://www.geoso2.es'>GEOSO2</a> "
  title: "Apuntes guía Expresión Gráfica <br>"
  #author: "<img src='images/00-00-A-hypatia.jpeg' width='700px'><br>María Jesús García García mariajesus.garcia.garcia@upm.es <br><br> Jose Luis Perez Benedito <br>joseluis.perez@upm.es <br> <br> Carolina Echavarría Caballero <br>carolina.echavarria@upm.es> <br><br> Luis Izquierdo Mesa <br>luis.izquierdo@upm.es <br><br> Dpto de Ingeniería y Gestión Forestal y Ambiental <br>E.T.S.I. Montes, Forestal y del Medio Natural<br>Universidad Politécnica de Madrid"
  author: "<a href='https://www.geoso2.es' target='_blank'><img src='images/authors2.png' width='500px'></a>"
  #date: "9/8/2024"
  chapters:
    - index.qmd
    - 01-normalizacion.qmd
    #- 02-proyecciones.qmd
    - 01-04-proyecciones.qmd
    - 03-geometria-constructiva.qmd
    # - part: "Conocimientos previos"
    #   chapters: 
    #     - 00-01-conocimientos-previos.qmd
    # - part: "Introducción"
    #   chapters:
    #     - 01-01-instrumentos.qmd
    #     - 01-02-lenguaje.qmd
    #     - 01-03-normalizacion.qmd
    #     - 01-04-proyecciones.qmd
    #     #- tricks/010-cuadradoFacil.qmd
    # #- part: "Sistema Diédrico"
    
    
    #- intro.qmd
    #- summary.qmd
    #- references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - r4ds.scss
    code-link: true
    number-sections: true

    author-meta: "Maria Jesús García García , Jose Luis Perez Benedito, and Luis Izquierdo Mesa"
    #include-in-header: "plausible.html"
    callout-appearance: simple

    # include-in-header: bootstrap-includes.html
editor: visual



