project:
  type: book

book:
  #title: "Apuntes guía Expresión Gráfica <br>  Grupo investigación <a href='https://www.geoso2.es'>GEOSO2</a> "
  title: "Apuntes guía Expresión Gráfica V 0.01<br>"
  #author: "<img src='images/00-00-A-hypatia.jpeg' width='700px'><br>María Jesús García García mariajesus.garcia.garcia@upm.es <br><br> Jose Luis Perez Benedito <br>joseluis.perez@upm.es <br> <br> Carolina Echavarría Caballero <br>carolina.echavarria@upm.es> <br><br> Luis Izquierdo Mesa <br>luis.izquierdo@upm.es <br><br> Dpto de Ingeniería y Gestión Forestal y Ambiental <br>E.T.S.I. Montes, Forestal y del Medio Natural<br>Universidad Politécnica de Madrid"
  author: "<a href='https://www.geoso2.es' target='_blank'><img src='images/authors2.png' width='500px'></a>"
  #date: "9/8/2024"
  chapters:
    - index.qmd
    - part: "Bloque 1. Introducción a la Expresión Gráfica"
      chapters:
        - 01-01-lenguaje-tecnica.qmd
        - 03-geometria-constructiva.qmd
        - 01-normalizacion.qmd
        - 01-04-croquizacion.qmd
    - part: "Bloque 2. Fundamentos de los Sistemas de Representación"
      chapters:
        - 04-sistemas-representacion.qmd
        - 04-01-diedrico.qmd
        - 04-02-axonometrico.qmd
        - 04-04-perspectiva-conica.qmd
    - part: "Bloque 3. Representación Gráfica de la Información Ambiental"
      chapters:
        - 04-03-planos-acotados.qmd
        - 03-planos-acotados/04-03-00-fundamentos.qmd
        - 03-planos-acotados/04-03-01-graduacion.qmd
        - 03-planos-acotados/04-03-02-DefinicionPlanos.qmd
        - 03-planos-acotados/04-03-04-curvado-planos.qmd
        - 03-planos-acotados/04-03-02-vaguadas-divisorias.qmd
        - 03-planos-acotados/04-03-03-perfiles-longitudinales.qmd
        - 03-planos-acotados/04-03-04-explanaciones-horizontales.qmd
        - 03-planos-acotados/04-03-05-explanaciones-pendiente.qmd
    - part: "Bloque 4. Elaboración de Planos"
      chapters:
        - 04-elaboracion-planos/04-01-normativa.qmd
        - 04-elaboracion-planos/04-02-situacion-localizacion.qmd
        - 04-elaboracion-planos/04-03-estructuras-infraestructuras.qmd
        - 04-elaboracion-planos/04-04-conjunto-despiece.qmd
        - 04-elaboracion-planos/04-05-detalle.qmd
        - 04-elaboracion-planos/04-06-cartografia-ambiental-forestal.qmd
    - part: "Bloque 5. Representación Gráfica Digital"
      chapters:
        - 05-representacion-digital/05-01-cad.qmd
        - 05-representacion-digital/05-02-sig.qmd
        - 05-representacion-digital/05-03-bim-gis.qmd
  appendices:
    - anexos/anexo-videos-autocad.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - r4ds.scss
    code-link: true
    number-sections: false
    number-depth: 2
    toc: true
    toc-depth: 3
    toc-expand: true

    author-meta: "Maria Jesús García García , Jose Luis Perez Benedito, and Luis Izquierdo Mesa"
    #include-in-header: "plausible.html"
    callout-appearance: simple

    # include-in-header: bootstrap-includes.html
editor: visual
