project:
  type: book

book:
  title: "¿Qué título le ponemos a esto?"
  author: "Norah Jones"
  date: "6/18/2024"
  chapters:
    - part: 01-00-part1.qmd
      chapters: 
        - 01-01-Titulo1.qmd
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



